#!/bin/sh

reset

MY_HOME=/home/goghor;
WORKING_DIR=$MY_HOME/Android;
KERNEL_DIR=$PWD;
KERNEL_IMG=$KERNEL_DIR/arch/arm64/boot/Image;
KERNEL_DTB=$KERNEL_DIR/arch/arm64/boot/dt.img;
DTBTOOL=$KERNEL_DIR/dtbTool;
TOOLCHAIN_DIR=$WORKING_DIR/Toolchains;
OUT_DIR=$MY_HOME/Public/Kenzo/Kernel/Out;
MODULES_DIR=$OUT_DIR/system/lib/modules;

BUILD_START=$(date +"%s");
blue='\033[0;34m';
cyan='\033[0;36m';
yellow='\033[0;33m';
red='\033[0;31m';
nocol='\033[0m';

THREADS=16;

# LINARO 6.3.1
# export CROSS_COMPILE=$TOOLCHAIN_DIR/aarch64-linux-android-6.3.1-linaro/bin/aarch64-linux-gnu-;
# export LD_LIBRARY_PATH=$TOOLCHAIN_DIR/aarch64-linux-android-6.3.1-linaro/lib/;
# STRIP=$TOOLCHAIN_DIR/aarch64-linux-android-6.3.1-linaro/bin/aarch64-linux-gnu-strip;

# AOSP 4.9
export CROSS_COMPILE=$TOOLCHAIN_DIR/aarch64-linux-android-4.9/bin/aarch64-linux-android-;
export LD_LIBRARY_PATH=$TOOLCHAIN_DIR/aarch64-linux-android-4.9/lib/;
STRIP=$TOOLCHAIN_DIR/aarch64-linux-android-4.9/bin/aarch64-linux-android-strip;

export ARCH=arm64;
export SUBARCH=arm64;
export KBUILD_BUILD_USER="MOVZX";
export KBUILD_BUILD_HOST="Telegram.org";
export LOCALVERSION="™";
# export LOCALVERSION="!";

KERNEL_NAME="Kenzo_CM-14.1_Darkness";
BUILD_DATE=-$(date +"%Y-%m-%d"-%H%M)-;
KERNEL_VER=$KERNEL_NAME$BUILD_DATE;

echo -e "**********************************************************************************************";
echo "                                                                                              ";
echo "                                  Compiling Darkness™ Kernel                                  ";
echo "                                                                                              ";
echo -e "**********************************************************************************************";
#
make clean -j8 && make clean mrproper -j8 && rm arch/arm/boot/dts/*.dtb
#
reset
#
echo 68 > .version;
echo "";
# make darkness_defconfig;
# make akuma_defconfig;
make kenzo_defconfig;
echo "";
make -j$THREADS;
# make Image -j$THREADS;
# echo "";
# make dtbs -j$THREADS;
# echo "";
# make modules -j$THREADS;
echo "";
if ! [ -a $KERN_IMG ]; then
	echo -e "$red Kernel Compilation failed!$nocol";
fi;
echo "";
$DTBTOOL -2 -o $KERNEL_DTB -s 2048 -p $KERNEL_DIR/scripts/dtc/ $KERNEL_DIR/arch/arm/boot/dts/;
echo "";

# echo "Copying Modules";
# rm $MODULES_DIR/*.ko;
# find . -name 'wlan.ko' -exec mv {} $MODULES_DIR/ \;
# cd $MODULES_DIR;
# echo "Stripping Modules";
# $STRIP --strip-unneeded *.ko;
# cp wlan.ko pronto/pronto_wlan.ko
# echo "";

# echo "Creating flashable ZIP";
cd $OUT_DIR;
# rm $KERNEL_NAME*.zip;
rm ./tools/Image;
rm ./tools/dt.img;
mv $KERNEL_IMG tools/Image;
mv $KERNEL_DTB tools/dt.img;
# zip -r `echo $KERNEL_VER`.zip *;
echo "";

BUILD_END=$(date +"%s");
DIFF=$(($BUILD_END - $BUILD_START));

echo -e "$yellow Build completed in $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds.$nocol";
echo "";
echo -e "**********************************************************************************************";
echo "                                                                                              ";
echo -e "$blue                                    Enjoy Darkness™ Kernel                                    $nocol";
# echo -e "$cyan                   $KERNEL_VER.zip                      $nocol";
echo "                                                                                              ";
echo -e "**********************************************************************************************"

cd $KERNEL_DIR
